# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: so.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='so.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x08so.proto\"\xcc\x02\n\nSalesModel\x12\x31\n\x0epartner_detail\x18\x01 \x01(\x0b\x32\x19.SalesModel.PartnerDetail\x12\x32\n\x0fproduct_details\x18\x02 \x01(\x0b\x32\x19.SalesModel.ProductDetail\x12\x32\n\x0fpayment_details\x18\x03 \x01(\x0b\x32\x19.SalesModel.PaymentDetail\x12\x0f\n\x07test_id\x18\x04 \x01(\x05\x1a)\n\rPartnerDetail\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a)\n\rProductDetail\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\x05\x1a<\n\rPaymentDetail\x12\x14\n\x0cinstallments\x18\x01 \x01(\x05\x12\x15\n\rinterval_days\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SALESMODEL_PARTNERDETAIL = _descriptor.Descriptor(
  name='PartnerDetail',
  full_name='SalesModel.PartnerDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SalesModel.PartnerDetail.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='SalesModel.PartnerDetail.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=240,
)

_SALESMODEL_PRODUCTDETAIL = _descriptor.Descriptor(
  name='ProductDetail',
  full_name='SalesModel.ProductDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sku', full_name='SalesModel.ProductDetail.sku', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qty', full_name='SalesModel.ProductDetail.qty', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=283,
)

_SALESMODEL_PAYMENTDETAIL = _descriptor.Descriptor(
  name='PaymentDetail',
  full_name='SalesModel.PaymentDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='installments', full_name='SalesModel.PaymentDetail.installments', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval_days', full_name='SalesModel.PaymentDetail.interval_days', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=345,
)

_SALESMODEL = _descriptor.Descriptor(
  name='SalesModel',
  full_name='SalesModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partner_detail', full_name='SalesModel.partner_detail', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_details', full_name='SalesModel.product_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payment_details', full_name='SalesModel.payment_details', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test_id', full_name='SalesModel.test_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SALESMODEL_PARTNERDETAIL, _SALESMODEL_PRODUCTDETAIL, _SALESMODEL_PAYMENTDETAIL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=345,
)

_SALESMODEL_PARTNERDETAIL.containing_type = _SALESMODEL
_SALESMODEL_PRODUCTDETAIL.containing_type = _SALESMODEL
_SALESMODEL_PAYMENTDETAIL.containing_type = _SALESMODEL
_SALESMODEL.fields_by_name['partner_detail'].message_type = _SALESMODEL_PARTNERDETAIL
_SALESMODEL.fields_by_name['product_details'].message_type = _SALESMODEL_PRODUCTDETAIL
_SALESMODEL.fields_by_name['payment_details'].message_type = _SALESMODEL_PAYMENTDETAIL
DESCRIPTOR.message_types_by_name['SalesModel'] = _SALESMODEL

SalesModel = _reflection.GeneratedProtocolMessageType('SalesModel', (_message.Message,), dict(

  PartnerDetail = _reflection.GeneratedProtocolMessageType('PartnerDetail', (_message.Message,), dict(
    DESCRIPTOR = _SALESMODEL_PARTNERDETAIL,
    __module__ = 'so_pb2'
    # @@protoc_insertion_point(class_scope:SalesModel.PartnerDetail)
    ))
  ,

  ProductDetail = _reflection.GeneratedProtocolMessageType('ProductDetail', (_message.Message,), dict(
    DESCRIPTOR = _SALESMODEL_PRODUCTDETAIL,
    __module__ = 'so_pb2'
    # @@protoc_insertion_point(class_scope:SalesModel.ProductDetail)
    ))
  ,

  PaymentDetail = _reflection.GeneratedProtocolMessageType('PaymentDetail', (_message.Message,), dict(
    DESCRIPTOR = _SALESMODEL_PAYMENTDETAIL,
    __module__ = 'so_pb2'
    # @@protoc_insertion_point(class_scope:SalesModel.PaymentDetail)
    ))
  ,
  DESCRIPTOR = _SALESMODEL,
  __module__ = 'so_pb2'
  # @@protoc_insertion_point(class_scope:SalesModel)
  ))
_sym_db.RegisterMessage(SalesModel)
_sym_db.RegisterMessage(SalesModel.PartnerDetail)
_sym_db.RegisterMessage(SalesModel.ProductDetail)
_sym_db.RegisterMessage(SalesModel.PaymentDetail)


# @@protoc_insertion_point(module_scope)
